name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: apt install xorg-dev
    - name: Run tests
      working-directory: ./src-tauri
      run: cargo test --verbose
    - name: Run clippy
      run: cargo clippy
